# Generated by Django 2.2.3 on 2019-07-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_auto_20190710_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='right_answer',
            field=models.CharField(choices=[(models.CharField(max_length=100), 'answer1'), (models.CharField(max_length=100), 'answer2'), (models.CharField(max_length=100), 'answer3'), (models.CharField(max_length=100), 'answer4')], max_length=20),
        ),
    ]
