# Generated by Django 2.2.3 on 2019-09-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_auto_20190710_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='track',
        ),
        migrations.AddField(
            model_name='course',
            name='track',
            field=models.ManyToManyField(to='tracks.track'),
        ),
    ]
