# Generated by Django 2.2.3 on 2019-09-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_auto_20190901_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='bio',
            field=models.URLField(),
        ),
    ]
