# Generated by Django 2.2.3 on 2019-09-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_auto_20190902_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='bio',
            new_name='link',
        ),
    ]
