# Generated by Django 2.2.3 on 2019-09-02 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0008_auto_20190902_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='watching_users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
