# Generated by Django 2.2.3 on 2019-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0009_lesson_watching_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='right_answer',
            field=models.CharField(choices=[(models.CharField(max_length=100), 'answer1'), (models.CharField(max_length=100), 'answer2'), (models.CharField(max_length=100), 'answer3'), (models.CharField(max_length=100), 'answer4')], default=models.CharField(max_length=100), max_length=20),
        ),
    ]
