# Generated by Django 2.2.3 on 2019-09-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_auto_20190903_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='right_answer',
            field=models.CharField(choices=[(models.CharField(max_length=100), 'answer1'), (models.CharField(max_length=100), 'answer2'), (models.CharField(max_length=100), 'answer3'), (models.CharField(max_length=100), 'answer4')], default=models.CharField(max_length=100), max_length=20, null=True),
        ),
    ]
