# Generated by Django 2.2.3 on 2019-09-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0011_auto_20190903_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='answer1',
        ),
        migrations.AlterField(
            model_name='exam',
            name='right_answer',
            field=models.CharField(choices=[('sdasdas', 'answer1'), (models.CharField(max_length=100), 'answer2'), (models.CharField(max_length=100), 'answer3'), (models.CharField(max_length=100), 'answer4')], default='sdasdas', max_length=20, null=True),
        ),
    ]
