# Generated by Django 2.1.4 on 2019-09-03 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0012_auto_20190903_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='answer1',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='right_answer',
            field=models.CharField(blank=True, choices=[('answer1', 'answer1'), ('answer2', 'answer2'), ('answer3', 'answer3'), ('answer4', 'answer4')], max_length=20, null=True),
        ),
    ]
