# Generated by Django 2.1.4 on 2019-09-05 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0013_auto_20190903_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='succeeded_users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
