# Generated by Django 2.2.3 on 2020-01-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0019_exam_result_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='designed_by',
            field=models.CharField(default='mosta', max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='position',
            field=models.CharField(default='developer', max_length=100),
        ),
    ]
