# Generated by Django 2.2.3 on 2020-01-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0020_auto_20200122_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(blank=True, upload_to='tracks'),
        ),
    ]
