# Generated by Django 2.2.3 on 2020-01-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0021_track_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='designed_by',
        ),
        migrations.RemoveField(
            model_name='track',
            name='position',
        ),
        migrations.AddField(
            model_name='track',
            name='points',
            field=models.TextField(blank=True),
        ),
    ]
