# Generated by Django 2.2.3 on 2020-01-23 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_teacher'),
        ('tracks', '0022_auto_20200122_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.teacher'),
        ),
    ]
