# Generated by Django 2.2.3 on 2020-02-04 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0025_auto_20200204_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='succeeded_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
