# Generated by Django 2.2.3 on 2020-01-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('fb', models.CharField(max_length=200)),
                ('ldn', models.CharField(max_length=200)),
                ('tw', models.CharField(max_length=200)),
            ],
        ),
    ]
