# Generated by Django 2.2.3 on 2020-01-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(null=True, upload_to='teachers'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='img',
            field=models.ImageField(null=True, upload_to='teachers'),
        ),
    ]
